version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
    ports:
      - "5000:5000"
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge